name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  setup:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the code
    - uses: actions/checkout@v4

    ##Install the nodes js 
    - name: setup nodes js 
      uses: actions/setup-node@v4
      with:
        version: 18

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:

    #build the docker file
    - name: checkout the code
      uses: actions/checkout@v4

    #login to docker
    - name: login to docker hub
      uses: actions/login-action@v3
      with:
        username: ${{secret.USERNAME}}
        password: ${{secret.PASSWORD}}
