name: Docker Image CI

on:
  push:
    branches: [ "master" ]



permissions:
  contents: read
  security-events: write # Required for the Trivy action to upload results to the Security tab


jobs:
  setup:
    runs-on: self-hosted
    
    steps:

    - name: change the permission of the docker file
      run: sudo chmod -R 777 /home/lokesh/actions-runner/_work/nodejs-application/nodejs-application/.scannerwork 
    
    - name: checkout the code
      uses: actions/checkout@v4



    ##Install the nodes js 
    - name: setup nodes js 
      uses: actions/setup-node@v4
      with:
        node-version: 18


  sonarqube:
    runs-on: self-hosted
    needs: setup
    steps:
    - name: checkout the code
      uses: actions/checkout@v4

    - name: setup sonarqube
      uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      with:
        args:
          -Dsonar.projectKey=nodejs
        

#    - name: run sonarqube
#      run: |
#        sonar-scanner -Dsonar.projectKey=sample-nodejs -Dsonar.sources=. -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN



  build:
    runs-on: self-hosted
    needs: sonarqube
    steps:

    - name: change the permission of the docker file
      run: sudo chmod -R 777 /home/lokesh/actions-runner/_work/nodejs-application/nodejs-application/.scannerwork 

    #checkout the docker file
    - name: checkout the code
      uses: actions/checkout@v4




    #login to docker
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

    #build any push the code
    - name: build and push the code
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs:${{github.run_id}}


  trivy_scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs:${{github.run_id}}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          sarif_file: 'trivy-results.sarif'



  deploy:
    runs-on: self-hosted
    needs: trivy_scan
    steps:
    - name: deploy the code
      run: |
        docker run -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs:${{github.run_id}}


        



