name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout the code
      uses: actions/checkout@v4

    ##Install the nodes js 
    - name: setup nodes js 
      uses: actions/setup-node@v4
      with:
        version: 18

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:

    #checkout the docker file
    - name: checkout the code
      uses: actions/checkout@v4

    #login to docker
    - name: login to docker hub
      uses: actions/login-action@v3
      with:
        username: ${{secret.DOCKERHUB_USERNAME}}
        password: ${{secret.DOCKERHUB_PASSWORD}}

    #build any push the code
    - name: build and push the code
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockefile
        push: true
        tags: ${{secret.DOCKERHUB_USERNAME}}/sample-nodejs:${{github.run_id}}
